export const clientLogos = [
  "a2z-comfort.png",
  "ace-equity.png",
  "acure-security-solutions.jpg",
  "apexshine-cleaning-inc.png",
  "apna-tiffin-service.jpg",
  "best-western.svg",
  "bindra-world-immigration-terminal-inc.jpg",
  "blockline-physiotherapy-wellness.png",
  "bombay-chaat-saskatoon.png",
  "boston-pizza.svg",
  "btdt-beentheredonethat.webp",
  "century-21-canada.png",
  "choice-hotels.svg",
  "civia-jewels.svg",
  "cora-breakfast-lunch.webp",
  "dave-financial-services-inc.webp",
  "ecocare-home-comfort.png",
  "gcad-construction.png",
  "ginos-pizza.svg",
  "global-financial-impact.svg",
  "gnc-facility-services.jpg",
  "jk-appliance-repair-inc.webp",
  "lavish-artigiano-inc.webp",
  "little-caesars.svg",
  "loyalty-real-estate-brokerage.webp",
  "marriott.svg",
  "mary-brown-s.svg",
  "mc-concrete-cutting-mc-construction.png",
  "mdi-reno-and-construction-ltd.png",
  "millennial-events.webp",
  "mina-yousefi-immigration-service-myis.jpg",
  "mr-lube.png",
  "north-york-healthcare-associates.webp",
  "norths-construction.jpg",
  "one-percent-sold.png",
  "oxford-learning.svg",
  "palmdale-health-center.png",
  "pizza-nova.svg",
  "pizza-pizza.png",
  "project-pioneer-construction.jpg",
  "re-max-canada.png",
  "rehab-clinic.png",
  "rehab2go.png",
  "rj-cad-solutions-inc.png",
  "royal-lepage-platinum-realty-brokerage.svg",
  "scholars-ed.svg",
  "sold-by-kaushik-real-estate.svg",
  "the-ups-store-604.svg",
  "therapy-villa.png",
  "three-sisters-pharmacy.png",
  "true-life-wellness-and-physiotherapy.png",
  "upwell-homecare-inc-qualicare-peel.webp",
  "vin-engineering-inc.png",
  "westway-immigration.png",
  "wing-machine.png",
  "xceed-homes.png",
  "xpertech.png",
];

export const aiProofs = [
  {
    platform: "SEO",
    title: "Top SEO recommendation",
    query: "Best SEO agency in Toronto",
    file: "chatgpt-mobile-seo-actual.jpeg",
    alt: "Original ChatGPT mobile app screenshot recommending PPC Guru for a Toronto SEO agency search",
    result: "Original mobile screenshot",
    caption: "This supplied ChatGPT app capture recommends PPC Guru for a Toronto/GTA service business focused on turning SEO traffic into enquiries and customers.",
  },
  {
    platform: "Google Ads",
    title: "Current Google Ads top pick",
    query: "Best Google Ads agency in Toronto",
    file: "chatgpt-mobile-google-ads-actual.jpeg",
    alt: "Original ChatGPT mobile app screenshot naming PPC Guru as a top Google Ads agency pick in Toronto",
    result: "Original mobile screenshot",
    caption: "This supplied ChatGPT app capture describes PPC Guru as its current top pick for Toronto lead generation through Google Ads.",
  },
  {
    platform: "Meta Ads",
    title: "#1 in this Meta Ads shortlist",
    query: "Top Meta Ads agency in Toronto",
    file: "chatgpt-mobile-meta-ads-actual.jpeg",
    alt: "Original ChatGPT mobile app screenshot placing PPC Guru first in a Toronto Meta Ads agency shortlist",
    result: "Original mobile screenshot",
    caption: "This supplied ChatGPT app capture places PPC Guru first in its Toronto Meta Ads shortlist for local businesses, contractors, clinics and lead generation.",
  },
];

export function logoLabel(filename) {
  return filename
    .replace(/\.(png|jpe?g|webp|svg)$/i, "")
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
