"use client";

import { useState } from "react";
import { motion } from "motion/react";
import { Loader2, Copy, Check, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

type Variation = { headlines: string[]; descriptions: string[] };

export function AdCopyGenerator() {
  const [business, setBusiness] = useState("");
  const [offer, setOffer] = useState("");
  const [platform, setPlatform] = useState<"google" | "meta">("google");
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [variations, setVariations] = useState<Variation[] | null>(null);
  const [aiPowered, setAiPowered] = useState(false);

  async function run(e: React.FormEvent) {
    e.preventDefault();
    setError(null);
    setVariations(null);
    setLoading(true);
    try {
      const res = await fetch("/api/ad-copy", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ business, offer, platform }),
      });
      const data = await res.json();
      if (!res.ok) setError(data.error || "Something went wrong.");
      else {
        setVariations(data.variations);
        setAiPowered(data.aiPowered);
      }
    } catch {
      setError("Network error. Please try again.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <div className="rounded-3xl border border-[var(--color-border)] bg-[var(--color-surface)] p-7 md:p-9">
      <form onSubmit={run} className="grid gap-4 md:grid-cols-2">
        <label className="block">
          <span className="mb-2 block text-sm font-medium text-[var(--color-ink-dim)]">Your business</span>
          <input value={business} onChange={(e) => setBusiness(e.target.value)} placeholder="e.g. Maple HVAC" className="w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-base)] px-4 py-3 text-[var(--color-ink)] outline-none focus:border-[var(--color-violet)]" />
        </label>
        <label className="block">
          <span className="mb-2 block text-sm font-medium text-[var(--color-ink-dim)]">Platform</span>
          <div className="grid grid-cols-2 gap-2">
            {(["google", "meta"] as const).map((p) => (
              <button key={p} type="button" onClick={() => setPlatform(p)} className={`rounded-xl border px-3 py-3 text-sm font-medium transition-colors ${platform === p ? "border-[var(--color-violet)] bg-[color-mix(in_srgb,var(--color-violet)_14%,transparent)] text-[var(--color-ink)]" : "border-[var(--color-border)] text-[var(--color-ink-dim)]"}`}>
                {p === "google" ? "Google Ads" : "Meta Ads"}
              </button>
            ))}
          </div>
        </label>
        <label className="block md:col-span-2">
          <span className="mb-2 block text-sm font-medium text-[var(--color-ink-dim)]">What are you advertising?</span>
          <input value={offer} onChange={(e) => setOffer(e.target.value)} placeholder="e.g. Furnace tune-ups and AC installation in Mississauga" className="w-full rounded-xl border border-[var(--color-border)] bg-[var(--color-base)] px-4 py-3 text-[var(--color-ink)] outline-none focus:border-[var(--color-violet)]" />
        </label>
        <div className="md:col-span-2">
          <Button type="submit" size="lg" disabled={loading} className="w-full sm:w-auto">
            {loading ? <><Loader2 size={18} className="animate-spin" /> Generating…</> : <>Generate ad copy <Sparkles size={16} /></>}
          </Button>
        </div>
      </form>

      {error && <p className="mt-4 rounded-lg bg-[color-mix(in_srgb,var(--color-danger)_12%,transparent)] px-4 py-3 text-sm text-[var(--color-danger)]">{error}</p>}

      {variations && (
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} className="mt-8 space-y-5">
          <p className="flex items-center gap-1.5 text-xs text-[var(--color-ink-faint)]">
            <Sparkles size={12} className="text-[var(--color-cyan-bright)]" />
            {aiPowered ? "Generated by Claude AI." : "Generated from a smart template (connect an API key for AI-written variations)."} Starting points our team refines — not guaranteed to convert.
          </p>
          {variations.map((v, i) => (
            <div key={i} className="rounded-2xl border border-[var(--color-border)] bg-[var(--color-base)] p-6">
              <p className="mb-3 text-xs font-semibold uppercase tracking-wide text-[var(--color-ink-faint)]">Variation {i + 1}</p>
              <div className="space-y-2">
                {v.headlines.map((h, j) => (
                  <CopyLine key={`h${j}`} text={h} tag={`H · ${h.length}/30`} />
                ))}
                {v.descriptions.map((d, j) => (
                  <CopyLine key={`d${j}`} text={d} tag={`D · ${d.length}`} muted />
                ))}
              </div>
            </div>
          ))}
          <div className="rounded-2xl border border-[var(--color-border-bright)] bg-[var(--color-base-2)] p-6 text-center">
            <p className="text-[var(--color-ink)]">Want copy that&apos;s tested and managed for you, not just generated?</p>
            <Button href="/contact" className="mt-4">Talk to our team</Button>
          </div>
        </motion.div>
      )}
    </div>
  );
}

function CopyLine({ text, tag, muted }: { text: string; tag: string; muted?: boolean }) {
  const [copied, setCopied] = useState(false);
  return (
    <div className="flex items-center justify-between gap-3 rounded-lg border border-[var(--color-border)] px-3 py-2">
      <span className={`text-sm ${muted ? "text-[var(--color-ink-dim)]" : "font-medium text-[var(--color-ink)]"}`}>{text}</span>
      <div className="flex shrink-0 items-center gap-2">
        <span className="text-[10px] text-[var(--color-ink-faint)]">{tag}</span>
        <button
          onClick={() => { navigator.clipboard.writeText(text); setCopied(true); setTimeout(() => setCopied(false), 1500); }}
          className="text-[var(--color-ink-faint)] hover:text-[var(--color-cyan-bright)]"
          aria-label="Copy"
        >
          {copied ? <Check size={14} className="text-[var(--color-success)]" /> : <Copy size={14} />}
        </button>
      </div>
    </div>
  );
}
