import type { ReactNode } from "react";
import Image from "next/image";
import Link from "next/link";
import { ArrowDown, ArrowRight, ArrowUpRight, Check, Plus, ShieldCheck } from "lucide-react";
import { type Service, services } from "@/lib/data/services";
import { industries } from "@/lib/data/industries";
import { getServiceContent } from "@/lib/data/service-content";
import { getServiceOffer, genericOffer } from "@/lib/data/service-offers";
import { getCaseStudies } from "@/lib/data/case-studies";
import { industriesForService, getServiceIndustryAngle, serviceIndustryLabel, type ServiceIndustryAngle } from "@/lib/data/service-industry";
import { getServiceIndustryParentAnchor } from "@/lib/data/service-industry-parent-links";
import { GOOGLE_PARTNER_PROFILE_URL, META_PARTNER_URL } from "@/lib/data/certifications";
import { googleAdsReports, metaAdsReports } from "@/lib/data/landing-paid-ads-reports";
import { googleBusinessProfile } from "@/lib/data/google-reviews";
import { companyFaqs } from "@/lib/data/company";
import { LeadCtaButton } from "@/components/shared/lead-cta";
import { InlineLinkText, type InlineLink } from "@/components/shared/inline-link-text";
import { LeadBand } from "@/components/sections/lead-band";
import { EstimateBand } from "@/components/sections/estimate-band";
import { LastReviewed } from "@/components/sections/service-aeo";
import { JsonLd } from "@/components/seo/json-ld";
import { faqSchema } from "@/lib/seo";
import { ServiceReportGallery } from "./service-report-gallery";
import { paidServicePlatforms, servicePresentation } from "./service-presentation";
import "./service-revamp.css";

type IndustryContext = { slug: string; name: string; label: string; angle: ServiceIndustryAngle; intro: string; definition: string; calculatorIndustry?: string };
type Crumb = { name: string; path: string };

export function ServiceSection({ id, kicker, title, intro, children, tone = "" }: { id?: string; kicker?: string; title: ReactNode; intro?: string; children?: ReactNode; tone?: string }) {
  return <section className={`srv-section ${tone ? `srv-${tone}` : ""}`} id={id}><div className="srv-wrap"><div className="srv-section-heading"><div>{kicker && <p className="srv-kicker">{kicker}</p>}<h2>{title}</h2></div>{intro && <p>{intro}</p>}</div>{children}</div></section>;
}

function Bullets({ items }: { items: string[] }) {
  return <ul className="srv-checks">{items.map((item) => <li key={item}><Check size={16} aria-hidden="true" /><span>{item}</span></li>)}</ul>;
}

function ServiceCta({ service, source, className = "", label }: { service: Service; source?: string; className?: string; label?: string }) {
  const offer = getServiceOffer(service.slug) ?? genericOffer;
  return <LeadCtaButton label={<>{label ?? offer.ctaLabel}<ArrowRight size={17} aria-hidden="true" /></>} source={source ?? offer.formSource} title={offer.popupTitle} blurb={offer.popupBody} submitLabel={offer.ctaLabel} className={`srv-button ${className}`} />;
}

export function ServiceTrust() {
  return <div className="srv-trust"><div className="srv-wrap"><span className="srv-trust-label">A partner you can look up.</span><a href={GOOGLE_PARTNER_PROFILE_URL} target="_blank" rel="noopener noreferrer"><Image src="/badges/reviews/google.svg" width={90} height={29} alt="Google" /><strong>Partner</strong><ArrowUpRight size={14} /></a><a href={META_PARTNER_URL} target="_blank" rel="noopener noreferrer"><Image src="/badges/meta-logo.svg" width={92} height={19} alt="Meta" /><span>Partner documentation</span><ArrowUpRight size={14} /></a><a href={googleBusinessProfile.url} target="_blank" rel="noopener noreferrer"><ShieldCheck size={19} /><span>Read our Google reviews</span><ArrowUpRight size={14} /></a></div></div>;
}

function HeroVisual({ service }: { service: Service }) {
  const presentation = servicePresentation[service.slug];
  const reports = service.slug === "google-ads" ? googleAdsReports : service.slug === "meta-ads" ? metaAdsReports : null;
  if (reports) return <figure className="srv-hero-proof"><div className="srv-proof-topline"><span>Inside the actual campaigns</span><span>{service.slug === "google-ads" ? "Google Ads" : "Meta Ads"}</span></div><a href="#results" className="srv-dashboard-fan" aria-label="Explore the supplied campaign reports">{[0, 3, 7].map((index, position) => <Image key={reports[index].src} className={`srv-fan-${position}`} src={reports[index].src} alt={reports[index].alt} width={reports[index].width} height={reports[index].height} sizes="(max-width: 600px) 135px, 170px" priority={position === 1} />)}<span className="srv-proof-open">See the full reports <ArrowUpRight size={15} /></span></a><figcaption>Real supplied dashboards. Individual campaign results vary.</figcaption></figure>;
  if (["seo", "web-design", "cro-landing-pages"].includes(service.slug)) return <figure className="srv-site-preview"><div className="srv-browser-bar"><span><i /><i /><i /></span><small>Landing page example</small></div><div className="srv-preview-image"><Image src="/images/home/ppc-guru-landing-page.jpg" alt="PPC Guru’s 100 Leads landing page with an offer, enquiry form and client evidence" width={1265} height={712} sizes="(max-width: 800px) 90vw, 570px" priority /></div><div className="srv-preview-notes"><span><Check size={14} /> Clear offer</span><span><Check size={14} /> Useful proof</span><span><Check size={14} /> Next step</span></div><figcaption>Our actual landing page. A design example, not a ranking or conversion-rate claim.</figcaption></figure>;
  const Icon = service.icon;
  return <figure className="srv-workflow"><div className="srv-workflow-brand">{presentation.logo ? <Image src={presentation.logo} width={50} height={50} alt={presentation.logoAlt ?? ""} /> : <Icon size={42} strokeWidth={1.5} aria-hidden="true" />}<span>{service.name}<small>The work, connected.</small></span></div><ol>{service.process.slice(0, 3).map((step, index) => <li key={step.step}><span>0{index + 1}</span><div><strong>{step.title}</strong><p>{step.body}</p></div>{index < 2 && <ArrowDown size={18} aria-hidden="true" />}</li>)}</ol><figcaption>Our proposed working process. Scope is agreed before work begins.</figcaption></figure>;
}

function ServiceHero({ service, industry, crumbs }: { service: Service; industry?: IndustryContext; crumbs: Crumb[] }) {
  const presentation = servicePresentation[service.slug];
  return <section className="srv-hero" id="top"><div className="srv-wrap"><nav className="srv-breadcrumbs" aria-label="Breadcrumb">{crumbs.map((crumb, index) => <span key={crumb.path}>{index > 0 && <span aria-hidden="true">/</span>}{index === crumbs.length - 1 ? <span aria-current="page">{crumb.name}</span> : <Link href={crumb.path}>{crumb.name}</Link>}</span>)}</nav><div className="srv-hero-grid"><div className="srv-hero-copy"><p className="srv-kicker">{presentation.logo && <Image src={presentation.logo} alt="" width={23} height={23} />}{industry?.label ?? service.name} · PPC Guru</p><h1>{industry ? <>{industry.label}.<br /><em>Built around your next customer.</em></> : <>{presentation.headline}<br /><em>{presentation.emphasis}</em></>}</h1><p className="srv-hero-description">{industry?.intro ?? service.hero}</p><div className="srv-actions"><ServiceCta service={service} source={industry ? `offer:${service.slug}:${industry.slug}` : service.slug === "google-ads" ? "offer:google-ads:flagship-hero" : undefined} /><a className="srv-text-link" href="#results">See the work <ArrowDown size={16} /></a></div><p className="srv-hero-note">Free review. Clear priorities. No obligation.</p><div className="srv-focus-line"><span>One connected approach</span><strong>{presentation.focus}</strong></div></div><HeroVisual service={service} /></div></div></section>;
}

function ServiceEvidence({ service, industry }: { service: Service; industry?: IndustryContext }) {
  const reports = service.slug === "google-ads" ? googleAdsReports : service.slug === "meta-ads" ? metaAdsReports : null;
  if (reports) return <ServiceSection id="results" kicker="Open the evidence" title={<>Real campaigns.<br /><em>See the whole picture.</em></>} intro={industry ? "A selection from our wider campaign portfolio. These reports show the named campaign accounts, not a promise for your industry or business." : "Look beyond a headline number. Explore original dashboards with the campaign context visible."} tone="sage"><ServiceReportGallery reports={reports} platform={service.slug === "google-ads" ? "Google Ads" : "Meta Ads"} /></ServiceSection>;
  const website = ["web-design", "cro-landing-pages"].includes(service.slug);
  return <ServiceSection id="results" kicker={website ? "Explore a live example" : "What you can inspect"} title={website ? <>See how the journey<br /><em>comes together.</em></> : <>Clear work.<br /><em>Visible progress.</em></>} intro={website ? "Explore a page we built: the offer, enquiry form, campaign screenshots and the path to the next step." : "Start with your baseline and agree what success means. Your reporting should show the work completed and the measures relevant to this service."} tone="sage"><div className="srv-evidence-split">{website ? <figure className="srv-evidence-preview"><Image src="/images/home/ppc-guru-landing-page.jpg" alt="Actual PPC Guru 100 Leads website design" width={1265} height={712} sizes="(max-width: 800px) 90vw, 650px" /><figcaption>Landing page example · designed by PPC Guru</figcaption></figure> : <div className="srv-measure-panel"><p className="srv-kicker">Measures for this service</p><Bullets items={service.metrics} /><p className="srv-fine">These are reporting measures, not claimed client results.</p></div>}<div className="srv-evidence-copy"><h3>Know what changed.<br />Know what happens next.</h3><p>Agree the starting point, the work in scope and how progress will be reviewed. We connect the activity to your business goals without treating every click or form fill as a sale.</p><ServiceCta service={service} source={`${(getServiceOffer(service.slug) ?? genericOffer).formSource}:dashboard`} /><Link className="srv-text-link" href="/google-ads-and-meta-ads#results">Explore our paid advertising reports <ArrowUpRight size={16} /></Link><p className="srv-fine">Google and Meta campaign reports are paid-advertising evidence; they do not establish results for {service.name.toLowerCase()}.</p></div></div></ServiceSection>;
}

function ServiceDeepContent({ service }: { service: Service }) {
  const content = getServiceContent(service.slug);
  const studies = getCaseStudies(service.caseStudySlugs);
  return <ServiceSection kicker="Go one level deeper" title={<>The detail behind<br /><em>the plan.</em></>} intro="Explore the checks, working rhythm and tools that can form part of your engagement. The final scope is agreed with you."><div className="srv-disclosures">
    {service.slug === "seo" && <details open><summary>SEO, answer engines and AI visibility<Plus size={19} /></summary><p>SEO improves the content and technical foundations search engines use to discover and understand your business. We review indexable service and location pages, answer-first copy, accurate business facts, first-hand evidence, internal links and crawl access alongside local search and technical performance. These foundations also make your content clearer for AI discovery. Inclusion in Google’s AI answers, ChatGPT or other AI responses is not guaranteed.</p><a className="srv-text-link" href="https://developers.google.com/search/docs/fundamentals/ai-optimization-guide" target="_blank" rel="noopener noreferrer">Google’s guidance on AI search visibility<ArrowUpRight size={16} /></a></details>}
    {service.auditChecklist && <details open><summary>What we audit first<Plus size={19} /></summary><div className="srv-detail-grid">{service.auditChecklist.map((group) => <div key={group.category}><h3>{group.category}</h3><Bullets items={group.items} /></div>)}</div></details>}
    {service.first30Days && <details><summary>The first 30 days<Plus size={19} /></summary><div className="srv-detail-grid">{service.first30Days.map((item) => <div key={item.window}><p className="srv-kicker">{item.window}</p><h3>{item.title}</h3><p>{item.body}</p></div>)}</div></details>}
    {service.optimizationCadence && <details><summary>How often we review and improve<Plus size={19} /></summary><div className="srv-detail-grid">{Object.entries(service.optimizationCadence).map(([window, items]) => <div key={window}><h3 className="srv-capitalize">{window}</h3><Bullets items={items} /></div>)}</div></details>}
    {service.aiAutomation && <details><summary>AI assistance, with human direction<Plus size={19} /></summary><div className="srv-detail-grid">{service.aiAutomation.map((item) => <div key={item.title}><h3>{item.title}</h3><p>{item.body}</p></div>)}</div></details>}
    {service.toolStack && <details><summary>The tools behind the work<Plus size={19} /></summary><div className="srv-detail-grid">{service.toolStack.map((group) => <div key={group.group}><h3>{group.group}</h3><p>{group.tools.join(" · ")}</p></div>)}</div></details>}
    {content?.comparison && <details><summary>Questions to ask when comparing providers<Plus size={19} /></summary><div className="srv-comparison">{content.comparison.map((row) => <div key={row.dimension}><h3>{row.dimension}</h3><p>{row.us}</p></div>)}</div><Link className="srv-text-link" href="/compare">Explore service and channel comparisons <ArrowRight size={16} /></Link></details>}
    {studies.length > 0 && <details><summary>Illustrative strategy examples<Plus size={19} /></summary><p>These existing guides use representative, anonymized scenarios. They explain an approach and are not verified client results.</p><div className="srv-link-list">{studies.map((study) => <Link key={study.slug} href={`/results/${study.slug}`}>{study.client}<ArrowUpRight size={16} /></Link>)}</div></details>}
  </div></ServiceSection>;
}

export function ServiceQuestions({ faqs, title, emitSchema = false }: { faqs: { q: string; a: string; link?: InlineLink }[]; title: string; emitSchema?: boolean }) {
  return <ServiceSection id="faq" kicker="Before you decide" title={title} intro="Straight answers about fit, scope and what working together involves.">{emitSchema && <JsonLd data={faqSchema(faqs)} />}<div className="srv-faqs">{faqs.map((faq, index) => <details key={faq.q} open={index === 0}><summary>{faq.q}<Plus size={19} /></summary><p><InlineLinkText text={faq.a} link={faq.link} /></p></details>)}</div></ServiceSection>;
}

function ServiceLocations({ service }: { service: Service }) {
  const content = getServiceContent(service.slug);
  const canLink = ["google-ads", "meta-ads", "seo"].includes(service.slug);
  return <ServiceSection kicker={content?.geoHeading ?? "Across the GTA & Canada"} title={<>Local understanding.<br /><em>A wider perspective.</em></>} intro={content?.geoBlurb ?? `${service.name} for businesses in Toronto, the Greater Toronto Area and across Canada.`}><div className="srv-location-links">{["Toronto", "Mississauga", "Brampton", "Vaughan", "Markham", "Hamilton", "Ottawa"].map((city) => canLink ? <Link key={city} href={`/${city.toLowerCase()}/${service.slug}`}>{city}<ArrowUpRight size={13} /></Link> : <span key={city}>{city}</span>)}<Link href="/locations">All service areas<ArrowRight size={14} /></Link></div></ServiceSection>;
}

export function ServiceExperience({ service, crumbs, industry }: { service: Service; crumbs: Crumb[]; industry?: IndustryContext }) {
  const content = getServiceContent(service.slug);
  const offer = getServiceOffer(service.slug) ?? genericOffer;
  const paidPlatform = paidServicePlatforms[service.slug as keyof typeof paidServicePlatforms];
  const industrySlugs = industriesForService(service.slug);
  const relatedIndustries = industries.filter((item) => item.services.includes(service.slug));
  const pageFaqs = content?.faqs ?? service.faqs;
  return <div className="service-revamp"><ServiceHero service={service} industry={industry} crumbs={crumbs} /><ServiceTrust />
    <section className="srv-definition"><div className="srv-wrap"><p className="srv-kicker">The short answer</p><h2>{industry ? `What is ${industry.label}?` : content?.definitionHeading ?? `What is ${service.name}?`}</h2><p><InlineLinkText text={industry?.definition ?? content?.definition ?? service.description} link={industry ? undefined : content?.definitionLink} /></p></div></section>
    <nav className="srv-page-nav" aria-label="On this page"><div className="srv-wrap"><a href="#results">The evidence</a><a href="#included">What’s included</a><a href="#process">How it works</a><a href="#faq">Your questions</a><a href="#lead-band">Get a free review<ArrowRight size={14} /></a></div></nav>
    <ServiceEvidence service={service} industry={industry} />
    {industry ? <ServiceSection id="included" kicker="Built for your market" title={<>The right service.<br /><em>The right context.</em></>} intro={`What good ${industry.label.toLowerCase()} looks like, and the practical choices behind it.`}><div className="srv-split"><div><h3>What good looks like</h3><Bullets items={industry.angle.goodPractices} /></div><div><h3>Best practices we apply</h3><Bullets items={industry.angle.bestPractices} /></div></div></ServiceSection> : <ServiceSection id="included" kicker="What changes" title={<>Less friction.<br /><em>More opportunity.</em></>} intro="Start with the problems holding you back. Then agree the work that will make the biggest difference."><div className="srv-split"><div className="srv-problem-panel"><h3>Does this sound familiar?</h3><ul>{service.symptoms.map((item) => <li key={item}>{item}</li>)}</ul></div><div><h3>What your engagement can include</h3><Bullets items={service.included} /><p className="srv-fine">Deliverables and priorities are confirmed in your agreed scope.</p></div></div><div className="srv-goal-strip"><span>What we work towards</span>{service.outcomes.map((item) => <p key={item}>{item}</p>)}</div></ServiceSection>}
    <ServiceSection kicker="The work behind the outcome" title={<>A clear scope.<br /><em>Nothing to guess.</em></>} intro={industry ? `The core ${service.name.toLowerCase()} work is adapted to your industry, service area and customer journey.` : "Concrete deliverables you can discuss, inspect and review. Start with the work your business needs."} tone="paper"><div className="srv-deliverables">{service.deliverables.map((item, index) => <article key={item.title}><span className="srv-number">{String(index + 1).padStart(2, "0")}</span><h3>{item.title}</h3><p>{item.body}</p></article>)}</div><div className="srv-inline-cta"><p>{offer.subhook}</p><ServiceCta service={service} source={industry ? `offer:${service.slug}:${industry.slug}` : `${offer.formSource}:included`} /></div></ServiceSection>
    <ServiceSection id="process" kicker="From the first conversation" title={<>Know the plan.<br /><em>See it move forward.</em></>}><ol className="srv-process">{service.process.map((step) => <li key={step.step}><span className="srv-number">{step.step}</span><h3>{step.title}</h3><p>{step.body}</p></li>)}</ol></ServiceSection>
    {industry ? <ServiceSection kicker="Set expectations early" title={<>Context before<br /><em>commitment.</em></>} tone="sage"><div className="srv-split"><div><h3>Industry planning context</h3><p className="srv-fine">Representative ranges and practices, not PPC Guru client results or guarantees. Confirm assumptions against your own market and baseline.</p><Bullets items={industry.angle.industryStandards} /></div><div><h3>What working together involves</h3><Bullets items={industry.angle.whatToExpect} /></div></div></ServiceSection> : <ServiceSection kicker="Choose the right approach" title={<>Built for your goals.<br /><em>Not a one-size plan.</em></>} tone="sage"><div className="srv-split"><div><h3>Who this is for</h3><Bullets items={service.whoFor} /></div><div><h3>Channels, formats and tactics</h3><div className="srv-tactics">{service.platforms.map((platform) => <div key={platform.name}><strong>{platform.name}</strong><p>{platform.body}</p></div>)}</div></div></div></ServiceSection>}
    <ServiceDeepContent service={service} />
    <ServiceSection id={paidPlatform ? undefined : "estimate"} kicker="Scope & reporting" title={<>Know what you’re paying for.<br /><em>Know what we’re measuring.</em></>} tone="paper"><div className="srv-split"><div><h3>Measures we review</h3><Bullets items={service.metrics} /></div><div><h3>What shapes your investment</h3><p>Fees depend on the work agreed. {paidPlatform ? "Advertising spend is separate from management fees and paid to the platform." : "Any software, production or third-party costs are confirmed with the scope."}</p><Bullets items={service.pricingFactors} /><Link className="srv-text-link" href="/pricing">How our pricing works<ArrowRight size={16} /></Link></div></div></ServiceSection>
    {paidPlatform && <div className="srv-estimate"><EstimateBand platform={paidPlatform} defaultIndustry={industry?.calculatorIndustry} title={<>Explore the budget.<br />Understand the assumptions.</>} intro="A planning calculator, not a forecast or a client result. Change the assumptions to see how traffic, conversion rate and customer value affect an illustrative scenario." /></div>}
    {!industry && <ServiceSection kicker={content?.industriesHeading ?? "Your industry matters"} title={<>The same discipline.<br /><em>A different playbook.</em></>} intro={content?.industriesBlurb}><div className="srv-industry-playbooks">{industrySlugs.length ? industrySlugs.map((slug) => { const angle = getServiceIndustryAngle(service.slug, slug)!; const label = serviceIndustryLabel(service.slug, slug); return <details key={slug}><summary>{label}<Plus size={18} /></summary><div className="srv-detail-grid">{([["What good looks like", angle.goodPractices], ["Best practices", angle.bestPractices], ["Planning benchmarks, not guarantees", angle.industryStandards], ["What to expect", angle.whatToExpect]] as [string, string[]][]).map(([heading, items]) => <div key={heading}><h3>{heading}</h3><Bullets items={items} /></div>)}</div><Link className="srv-text-link" href={`/services/${service.slug}/${slug}`}>Read the full {label} guide<ArrowRight size={16} /></Link></details>; }) : relatedIndustries.map((item) => <Link key={item.slug} href={`/industries/${item.slug}`}>{item.name}<ArrowUpRight size={17} /></Link>)}</div></ServiceSection>}
    {industry && <section className="srv-parent-links"><div className="srv-wrap"><Link href={`/services/${service.slug}`}>{getServiceIndustryParentAnchor(service.slug, industry.slug) ?? `Explore all ${service.name} services`}<ArrowRight size={17} /></Link><Link href={`/industries/${industry.slug}`}>{industry.name} marketing<ArrowRight size={17} /></Link></div></section>}
    <ServiceLocations service={service} /><ServiceQuestions faqs={pageFaqs} title={`${industry?.label ?? service.name}: your questions, answered.`} emitSchema={Boolean(industry)} />
    <div className="srv-lead"><LeadBand source={industry ? `offer:${service.slug}:${industry.slug}` : service.slug === "google-ads" ? "flagship:google-ads" : offer.formSource} title={industry ? `Plan your ${industry.label.toLowerCase()}` : offer.ctaLabel.replace(/^Get my /, "Get your ")} blurb={offer.popupBody} ctaLabel={offer.ctaLabel} points={["Review your current position", "Identify the most useful next steps", "Agree the fit and scope before starting"]} /></div>
    <div className="srv-end"><div className="srv-wrap"><p>A clearer next step starts with a conversation.</p><Link href="/contact">Talk to PPC Guru<ArrowUpRight size={18} /></Link><LastReviewed date="October 2026" /></div></div>
  </div>;
}

export function ServiceDirectory() {
  const groups = [{ title: "Be found.", intro: "Capture demand and build visibility where customers look.", slugs: ["google-ads", "seo", "microsoft-ads"] }, { title: "Create demand.", intro: "Give the right audience a reason to stop, consider and act.", slugs: ["meta-ads", "youtube-ads", "tiktok-ads", "linkedin-ads", "pinterest-ads", "creative"] }, { title: "Make the connection.", intro: "Turn interest into an enquiry, then connect the follow-up.", slugs: ["web-design", "cro-landing-pages", "crm", "ai-automation"] }];
  return <div className="service-revamp"><section className="srv-directory-hero"><div className="srv-wrap"><nav className="srv-breadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>/</span><span aria-current="page">Services</span></nav><p className="srv-kicker">Digital marketing services · PPC Guru</p><h1>The right work.<br /><em>In the right order.</em></h1><p>Connect the channels that bring people in with the website and follow-up that turn interest into opportunity. Start with your goal. Build the plan around it.</p><div className="srv-actions"><a className="srv-button" href="#services">Explore the services<ArrowDown size={17} /></a><Link className="srv-text-link" href="/free-audit">Find my starting point<ArrowRight size={17} /></Link></div><div className="srv-directory-platforms">{[["google-ads", "Google Ads"], ["meta", "Meta"], ["google", "Google"], ["youtube", "YouTube"], ["tiktok", "TikTok"], ["wordpress", "WordPress"]].map(([logo, label]) => <Image key={logo} src={`/platforms/${logo}.svg`} width={36} height={36} alt={label} />)}</div></div></section><ServiceTrust /><div id="services">{groups.map((group) => <ServiceSection key={group.title} kicker="One connected customer journey" title={group.title} intro={group.intro}><div className="srv-service-cards">{group.slugs.map((slug) => { const service = services.find((item) => item.slug === slug)!; const presentation = servicePresentation[slug]; const Icon = service.icon; return <Link key={slug} href={`/services/${slug}`}><span className="srv-service-card-icon">{presentation.logo ? <Image src={presentation.logo} alt="" width={33} height={33} /> : <Icon size={29} />}</span><h3>{service.name}</h3><p>{service.short}</p><span className="srv-text-link">Explore the service<ArrowUpRight size={16} /></span></Link>; })}</div></ServiceSection>)}</div><ServiceSection kicker="Start with the bottleneck" title={<>You don’t need everything.<br /><em>You need the right next step.</em></>} intro="Review the current journey before adding more channels. We look at the offer, traffic, website and follow-up to agree where to begin." tone="sage"><div className="srv-directory-actions"><Link className="srv-button" href="/free-audit">Get a free website & ads audit<ArrowRight size={17} /></Link><Link className="srv-text-link" href="/google-ads-and-meta-ads#results">Explore real campaign reports<ArrowUpRight size={17} /></Link></div></ServiceSection><ServiceQuestions faqs={companyFaqs} title="Digital marketing services: your questions, answered." emitSchema /><div className="srv-lead"><LeadBand source="services" title="Find your next growth opportunity" points={["Review your starting point", "Find the gap in the customer journey", "Agree clear next steps"]} /></div></div>;
}
