export const clientLogos = [
  "a2z-comfort.png",
  "ace-equity.png",
  "acure-security-solutions.jpg",
  "apexshine-cleaning-inc.png",
  "apna-tiffin-service.jpg",
  "best-western.svg",
  "bindra-world-immigration-terminal-inc.jpg",
  "blockline-physiotherapy-wellness.png",
  "bombay-chaat-saskatoon.png",
  "boston-pizza.svg",
  "btdt-beentheredonethat.webp",
  "century-21-canada.png",
  "choice-hotels.svg",
  "civia-jewels.svg",
  "cora-breakfast-lunch.webp",
  "dave-financial-services-inc.webp",
  "ecocare-home-comfort.png",
  "gcad-construction.png",
  "ginos-pizza.svg",
  "global-financial-impact.svg",
  "gnc-facility-services.jpg",
  "jk-appliance-repair-inc.webp",
  "lavish-artigiano-inc.webp",
  "little-caesars.svg",
  "loyalty-real-estate-brokerage.webp",
  "marriott.svg",
  "mary-brown-s.svg",
  "mc-concrete-cutting-mc-construction.png",
  "mdi-reno-and-construction-ltd.png",
  "millennial-events.webp",
  "mina-yousefi-immigration-service-myis.jpg",
  "mr-lube.png",
  "north-york-healthcare-associates.webp",
  "norths-construction.jpg",
  "one-percent-sold.png",
  "oxford-learning.svg",
  "palmdale-health-center.png",
  "pizza-nova.svg",
  "pizza-pizza.png",
  "project-pioneer-construction.jpg",
  "re-max-canada.png",
  "rehab-clinic.png",
  "rehab2go.png",
  "rj-cad-solutions-inc.png",
  "royal-lepage-platinum-realty-brokerage.svg",
  "scholars-ed.svg",
  "sold-by-kaushik-real-estate.svg",
  "the-ups-store-604.svg",
  "therapy-villa.png",
  "three-sisters-pharmacy.png",
  "true-life-wellness-and-physiotherapy.png",
  "upwell-homecare-inc-qualicare-peel.webp",
  "vin-engineering-inc.png",
  "westway-immigration.png",
  "wing-machine.png",
  "xceed-homes.png",
  "xpertech.png",
];

export const campaignResults = [
  {
    client: "MC Constructions",
    result: "36 conversations",
    cost: "CA$15.64 / conversation",
    spend: "CA$562.87 spent",
    file: "mc-constructions.jpeg",
    logo: "mc-concrete-cutting-mc-construction.png",
  },
  {
    client: "True Life Wellness",
    result: "93 form leads",
    cost: "CA$12.43 / lead",
    spend: "CA$1,156.04 spent",
    file: "true-life-wellness.jpeg",
    logo: "true-life-wellness-and-physiotherapy.png",
  },
  {
    client: "Projects Pioneer",
    result: "432 conversations",
    cost: "CA$23.98 / conversation",
    spend: "CA$10,360.52 spent",
    file: "projects-pioneer.jpeg",
    logo: "project-pioneer-construction.jpg",
  },
  {
    client: "MDI Reno",
    result: "51 Meta leads",
    cost: "CA$12.42 / lead",
    spend: "Multiple campaigns",
    file: "mdi-reno.jpeg",
    logo: "mdi-reno-and-construction-ltd.png",
  },
  {
    client: "GCAD Construction",
    result: "187 conversations",
    cost: "CA$27.47 / conversation",
    spend: "CA$5.14K spent",
    file: "gcad-construction.jpeg",
    logo: "gcad-construction.png",
  },
  {
    client: "Apna Tiffin Service",
    result: "160 conversations",
    cost: "CA$3.98 / conversation",
    spend: "CA$637.37 spent",
    file: "apna-tiffin-service.jpeg",
    logo: "apna-tiffin-service.jpg",
  },
  {
    client: "Ecocare",
    result: "1.1K form leads",
    cost: "CA$21.14 / lead",
    spend: "CA$23.17K spent",
    file: "ecocare.jpeg",
    logo: "ecocare-home-comfort.png",
  },
];

export function logoLabel(filename) {
  return filename
    .replace(/\.(png|jpe?g|webp|svg)$/i, "")
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
}
